---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: latest

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: centos-6.5
    run_list:
    - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[rackspace_gluster::default]
